### PR TITLE
Game versus

### PR DESCRIPTION
**Pull request by dante11111111111**

### CODE REVIEW

**Review by fesqvw — APPROVED** [review]
Good code, it allows for a lot of flexibility on the game side of the application.
A bit more commenting would be pleasing, but it is nevertheless very clear and understandable.

**Review by LeoLgdr — CHANGES_REQUESTED** [review]
overrall, good code,
 a small change is needed for coherence between game area and clickable area these values should be the same, right now game area is smaller which causes the position of the other players to be displayed inside the circle sometimes

you should explain the logic the pos and order logic, it is not trivial and needs some comments if you can

**Review by LeoLgdr — APPROVED** [review]
good fix, the values are still not equal but I assume this is on purpose, they should be close enough now

**Review by Blecoeur — APPROVED** [review]
Nice addings ! You can maybe try to add modularity in GameListActivity.
Also, it is very specific, but a variable called "nbEssai" is not very consistent with the other variable naming convention since it is in French.

**Pull request merged**
