### PR TITLE
Remember me button

### PR DESCRIPTION
**Pull request by Blecoeur**
Could really test the cache without mockito, but the remember me button should be working.

### CODE REVIEW

**Review by fesqvw — APPROVED** [review]
Very useful feature to have, completed in a clean way.
More comments would be useful.

**Review by LeoLgdr — CHANGES_REQUESTED** [review]
Good work overall, I list a few small fixes you should consider imo.
- Your test checkThatUserIsReadonly is synchronous and does not wait some time to check that the db has (not) been updated. The test could pass even if the user is not readonly and the db just did not update in time. 
- The name checkbox is not very explicit that it's bound to login in TempLoginActivity. In CompleteUser,
-  in method addFriend there is no need to check if the friend is present in the list or not, remove returns false if the friend is not present, which you can use to update the db if necessary. 
- There is some modularization possible in method initializeUser for the try catch blocks (use auxilliary method) in CompleteUser.

**Comment by Blecoeur** [comment]
> * Your test checkThatUserIsReadonly is synchronous and does not wait some time to check that the db has (not) been updated. The test could pass even if the user is not readonly and the db just did not update in time.
In fact, the modification I made are that when the user is in read only mode, the database is never reached. In the next sprint(s), I (we) will modify all tests depending on the database using Mockito.
> * The name checkbox is not very explicit that it's bound to login in TempLoginActivity.
In will modify it in the next commit. Thanks for the suggestion
> * In CompleteUser, in method addFriend there is no need to check if the friend is present in the list or not, remove returns false if the friend is not present, which you can use to update the db if necessary.
I will do the modification in the method removeFriend because in add friend, I cannot do it.
> * There is some modularization possible in method initializeUser for the try catch blocks (use auxilliary method) in CompleteUser.
It actually made me realize that the try catch blocks are actually useless. I will modify it in the next commit

**Review by Matthieu-Andre — APPROVED** [review]
Code looks good, 
Mockito will hopefully help us with database testing

**Review by LeoLgdr — APPROVED** [review]

**Pull request merged**
